import 'package:scholar_clone/presentation/widgets/app_drop_down.dart';

final List<DropDownModel> standardList = [
  const DropDownModel(id: 31, name: "NR"),
  const DropDownModel(id: 32, name: "JR"),
  const DropDownModel(id: 33, name: "SR"),
  const DropDownModel(id: 34, name: "1"),
  const DropDownModel(id: 35, name: "2"),
  const DropDownModel(id: 36, name: "3"),
  const DropDownModel(id: 37, name: "4"),
  const DropDownModel(id: 38, name: "5"),
  const DropDownModel(id: 39, name: "6"),
  const DropDownModel(id: 40, name: "7"),
  const DropDownModel(id: 41, name: "8"),
  const DropDownModel(id: 42, name: "9"),
  const DropDownModel(id: 43, name: "10"),
  const DropDownModel(id: 44, name: "11"),
  const DropDownModel(id: 45, name: "12"),
  const DropDownModel(id: 93, name: "Alumini"),
  const DropDownModel(id: 2269, name: "Soft Skill"),
  const DropDownModel(id: 2270, name: "Sports"),
  const DropDownModel(id: 2271, name: "Vocational Skill"),
  const DropDownModel(id: 2272, name: "Hobbies and Activities"),
  const DropDownModel(id: 2273, name: "Library"),
  const DropDownModel(id: 2292, name: "Non-Academic Skill"),
  const DropDownModel(id: 2305, name: "STEM Resources"),
  const DropDownModel(id: 3476, name: "SQAA"),
];

final List<DropDownModel> categoryList = [
  const DropDownModel(id: 1, name: "Open"),
  const DropDownModel(id: 2, name: "SC"),
  const DropDownModel(id: 3, name: "ST"),
  const DropDownModel(id: 4, name: "SEBC"),
  const DropDownModel(id: 5, name: "BC"),
  const DropDownModel(id: 6, name: "OBC"),
  const DropDownModel(id: 8, name: "GENERAL"),
  const DropDownModel(id: 9, name: "SBC"),
  const DropDownModel(id: 10, name: "OT"),
  const DropDownModel(id: 11, name: "Christian"),
  const DropDownModel(id: 12, name: "Muslim"),
  const DropDownModel(id: 13, name: "Jain"),
  const DropDownModel(id: 14, name: "Catholic"),
  const DropDownModel(id: 15, name: "Sikh"),
];
